### ISSUE TITLE
What is the "secret" var for in the example?

### ISSUE THREAD

**Issue by alexflint** [gernest/qlstore#1]
There is a line that reads `var secret = ...`. It doesn't seem to be used but perhaps it's meant to hint at something that I'm missing?

(Great project btw - exactly what I was looking for!)

**Comment by gernest** [comment]
@alexflint Thanks for bringing this to my attention.

Initially, I was thinking of using only one key for initializing securecookie codecs  hence the name secret. But then i thought the example might be confusing, so I added `var KeyPairs` instead and forgot to remove the `var secret`. This is also present in the tests, I'm going to remove it now!

It means a lot to me hearing that you like this

**Comment by gernest** [comment]
@alexflint I hope the answer was good enough! I'm closing this Issue now!

Thanks, again!
